# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0002_auto_20170907_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturantlocation',
            name='category',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
