# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0003_resturantlocation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturantlocation',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
