# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0004_auto_20170907_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturantlocation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resturantlocation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
