# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0005_auto_20170907_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturantlocation',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
