# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import resturants.validators


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0006_resturantlocation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturantlocation',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[resturants.validators.validate_category]),
        ),
    ]
